name: SAST-SNYK

on:
  pull:
    branches:
      - master

jobs: 
  snyk-code:
    name: Snyk Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
